sudo: required
language: node_js
node_js: '8'
git:
  depth: 1
cache:
  yarn: true
  directories:
  - node_modules
install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
- export PATH=$(yarn global bin):$PATH
script:
- yarn
- yarn test
