sudo: required
language: node_js
node_js: '8'
git:
  depth: 1
cache:
  yarn: true
  directories:
  - node_modules
script:
- (yarn || true) && yarn && yarn test
- test $TRAVIS_BRANCH = "master" && \
    git config --global user.name "${GH_NAME}" && \
    git config --global user.email "${GH_EMAIL}" && \
    echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc && \
    cd website && GIT_USER="${GH_NAME}" yarn run publish-gh-pages
